# Generated by Django 5.0.6 on 2024-07-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='desc',
        ),
        migrations.AddField(
            model_name='service',
            name='desc1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='desc2',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
