# Generated by Django 5.0.6 on 2024-07-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
